import { NonvoteRecord } from '../nonvoterecord'


export var NONVOTELIST: NonvoteRecord[] = [
{
voteRecordKey: "ps1v1vr1",
volunteerKey: "v1",
gePresVoteCouldNotVoteReason: null,
gePresVoteIntended: null,
gePresVoteLevelOfSupport: "Strongly Support",
pPresVoteCouldNotVoteReason: "Lines too Long",
pPresVoteIntended: "Berne Sanders",
pPresVote: null,
pCongressVote: null,
pPresVoteCastBy: null,
pPresVoteLevelOfSupport: "Strongly Support",
pPresVotePollingLocation: "This Location",
presFirst: "Bernie Sanders",
presSecond: "Jill Stein",
presThird: "None",
}, {
voteRecordKey: "ps1v1vr1",
volunteerKey: "v3",
gePresVoteCouldNotVoteReason: null,
gePresVoteIntended: null,
gePresVoteLevelOfSupport: "Strongly Support",
pPresVoteCouldNotVoteReason: "Lines too Long",
pPresVoteIntended: "Berne Sanders",
pPresVote: null,
pCongressVote: null,
pPresVoteCastBy: null,
pPresVoteLevelOfSupport: "Strongly Support",
pPresVotePollingLocation: "This Location",
presFirst: "Bernie Sanders",
presSecond: "Jill Stein",
presThird: "None",
},
{
voteRecordKey: "ps1v1vr1",
volunteerKey: "v2",
gePresVoteCouldNotVoteReason: null,
gePresVoteIntended: null,
gePresVoteLevelOfSupport: "Strongly Support",
pPresVoteCouldNotVoteReason: "Lines too Long",
pPresVoteIntended: "Berne Sanders",
pPresVote: null,
pCongressVote: null,
pPresVoteCastBy: null,
pPresVoteLevelOfSupport: "Strongly Support",
pPresVotePollingLocation: "This Location",
presFirst: "Bernie Sanders",
presSecond: "Jill Stein",
presThird: "None",
},
{
voteRecordKey: "ps1v1vr1",
volunteerKey: "v2",
gePresVoteCouldNotVoteReason: null,
gePresVoteIntended: null,
gePresVoteLevelOfSupport: "Strongly Support",
pPresVoteCouldNotVoteReason: "Lines too Long",
pPresVoteIntended: "Berne Sanders",
pPresVote: null,
pCongressVote: null,
pPresVoteCastBy: null,
pPresVoteLevelOfSupport: "Strongly Support",
pPresVotePollingLocation: "This Location",
presFirst: "Bernie Sanders",
presSecond: "Jill Stein",
presThird: "None",
}
] 

