import { VoteRecord } from '../voterecord'


export var VOTELIST: VoteRecord[] = [
{
voteRecordKey: "ps1v1vr1",
volunteerKey: "v1",
gePresVote: "Jill Stein",
gePresVoteCastBy: "Vote By Mail",
gePresVoteLevelOfSupport: "Strongly Support",
pPresVoteCouldNotVote: true,
pPresVoteCouldNotVoteReason: "Lines too Long",
pPresVoteIntended: "Berne Sanders",
pPresVote: null,
pCongressVote: null,
pPresVoteCastBy: null,
pPresVoteLevelOfSupport: "Strongly Support",
pPresVotePollingLocation: "This Location",
presFirst: "Bernie Sanders",
presSecond: "Jill Stein",
presThird: "None",
}, {
voteRecordKey: "ps1v1vr1",
volunteerKey: "v3",
gePresVote: "Jill Stein",
gePresVoteCastBy: "Vote By Mail",
gePresVoteLevelOfSupport: "Strongly Support",
pPresVoteCouldNotVote: true,
pPresVoteCouldNotVoteReason: "Lines too Long",
pPresVoteIntended: "Berne Sanders",
pPresVote: null,
pCongressVote: null,
pPresVoteCastBy: null,
pPresVoteLevelOfSupport: "Strongly Support",
pPresVotePollingLocation: "This Location",
presFirst: "Bernie Sanders",
presSecond: "Jill Stein",
presThird: "None",
}, {
voteRecordKey: "ps1v1vr1",
volunteerKey: "v2",
gePresVote: "Jill Stein",
gePresVoteCastBy: "Vote By Mail",
gePresVoteLevelOfSupport: "Strongly Support",
pPresVoteCouldNotVote: true,
pPresVoteCouldNotVoteReason: "Lines too Long",
pPresVoteIntended: "Berne Sanders",
pPresVote: null,
pCongressVote: null,
pPresVoteCastBy: null,
pPresVoteLevelOfSupport: "Strongly Support",
pPresVotePollingLocation: "This Location",
presFirst: "Bernie Sanders",
presSecond: "Jill Stein",
presThird: "None",
}
] 

